import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
  title: "Next Themes Clean Setup",
  description: "Generated by next-themes demo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen w-full dark:bg-gray-950 bg-amber-50 transition-all duration-700">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
