import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers"; // 👈 doğru Provider importu

export const metadata: Metadata = {
  title: "Next Themes Clean Setup",
  description: "Generated by next-themes demo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
